# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Gau-Syu"
title_separator          : "-"
name                     : "Xu Gao"
url                      : https://xinghuan-stear.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "xinghuan-stear/xinghuan-stear.github.io"
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true

# Profile
profile:
    name                 : "Gau, Syu"
    email                : "gausyu@gmail.com"
    description          : &description "personal description"
    image                : "img/xhs.png"
    cv                   : "cv.pdf"
    employer             : "UCSC"
    orcid                : "0000-0001-8284-6955"
    github               : "xinghuan-stear"


# Reading Files
include:
  - .htaccess
  - _pages
  - files
